import type { NextPage } from "next";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Head from "next/head";
import useSWR from "swr";

import List from "../components/List";
import Search from "../components/Search";
import styles from "../styles/Heros.module.css";

export async function getStaticProps({ locale }: any) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"])),
    },
  };
}

const Home: NextPage = () => {
  // Load Language
  const { t } = useTranslation("common");

  // Fetch Data
  const { data, error } = useSWR(
    "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/all.json"
  );

  if (error) return <>An error has occurred.</>;
  if (!data) return <>Loading...</>;

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>{t("title")}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <div className={styles.grid}>
            <div className={styles.paper}>
              <Search />
              <List items={data} />
            </div>
          </div>
        </main>
      </div>
    </>
  );
};

export default Home;
