import type { NextPage } from "next";
import Head from "next/head";

import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

import Heros from "../components/Heros";
import styles from "../styles/Heros.module.css";

export async function getStaticProps({ locale }: any) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"])),
    },
  };
}

const Home: NextPage = () => {
  // Load Language
  const { t } = useTranslation("common");

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>{t("title")}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <div className={styles.grid}>
            <div className={styles.paper}>
              <Heros />
            </div>
          </div>
        </main>
      </div>
    </>
  );
};

export default Home;
